export const SELECTOR = {
    inputOrigin:'//*[@id="origin"]',
    inputDestination:'//*[@id="destination"]',
    basicTariffPlan:'//*[@id="planes-opciones_i_1"]//*[@data-titulo-tarifa="Básico"]',
    ticketsAvailable:'//*[@class="row selectedTren"]',
    buttonPersonalizaViaje:'//*[@id="submitpersonaliza"]',
    originSearchResults:'//*[@id="awesomplete_list_1"]//li',
    destinationSearchResults:'//*[@id="awesomplete_list_2"]//li',
    inputCardNumber:'//*[@id="inputCard"]',
    inputExpirationMonth:'//*[@id="cad1"]',
    inputExpirationYear:'//*[@id="cad2"]',
    inputCVV:'//*[@id="codseg"]',
    modalLabel:'//*[@id="myModalLabel"]',
    errorRS18:'//*[@id="myModalBody"]//*[contains(text(),\'Tarjeta no soportada\')]',
}